server:
    applicationConnectors:
        - type: http
          port: 8080
    adminConnectors:
        - type: http
          port: 8081
logging:
  level: INFO
  loggers:
    org.linagora.linshare.thumbnail.server: INFO
  appenders:
  - type: console
    threshold: WARN
    target: stderr
